#! /bin/sh
### BEGIN INIT INFO
# Provides: WebSocketServer
# Required-Start: $syslog
# Required-Stop:  $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: WebSocketServer
# Description:
### END INIT INFO

case "$1" in
start)
echo "WebSocketServer wird gestartet"
# Starte Programm
#/home/pi/WebSocketsServer/build/WebSocketsServer
/home/pi/Dobby/build/Dobby
;;

stop)
echo "WebSocketServer wird beendet"
# Beende Programm
killall WebSocketsServer
;;

*)
echo "Benutzt: /etc/init.d/WebSocketsServer { start|stop }"
exit 1
;;
esac
exit 0
